# FROM keycloak/keycloak:24.0.2
# COPY ./realm-export.json /tmp/realm-export.json
# ENV KEYCLOAK_IMPORT /tmp/realm-export.json
FROM keycloak/keycloak:24.0.2
COPY ./realm-export.json /opt/jboss/keycloak/standalone/configuration/realm-export.json
CMD [ "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/opt/jboss/keycloak/standalone/configuration/realm-export.json", "start-dev"]
