const createColorFunction = (colorName) => jest.fn((msg) => `[${colorName.toUpperCase()}] ${msg}`);

module.exports = {
  grey: createColorFunction('grey'),
  gray: createColorFunction('gray'),
  greenBright: createColorFunction('greenBright'),
  green: createColorFunction('green'),
  red: createColorFunction('red'),
  yellow: createColorFunction('yellow'),
  blue: createColorFunction('blue'),
  cyan: createColorFunction('cyan'),
  magenta: createColorFunction('magenta'),
  white: createColorFunction('white'),
  black: createColorFunction('black'),
  bgRed: createColorFunction('bgRed'),
  bgGreen: createColorFunction('bgGreen'),
  bgYellow: createColorFunction('bgYellow'),
  bgBlue: createColorFunction('bgBlue'),
  bgCyan: createColorFunction('bgCyan'),
  bgMagenta: createColorFunction('bgMagenta'),
  bgWhite: createColorFunction('bgWhite'),
  stderr: createColorFunction('stderr'),
  bold: createColorFunction('bold'),
  dim: createColorFunction('dim'),
  italic: createColorFunction('italic'),
  underline: createColorFunction('underline'),
  inverse: createColorFunction('inverse'),
  stripColor: jest.fn((msg) => msg),
  supportsColor: { level: 3 },
};